FROM golang:1.9 as builder

WORKDIR /go/src/github.com/idcrosby/go-example-webserver/
COPY *.go ./
COPY *.txt ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .

FROM scratch

COPY --from=builder /go/src/github.com/idcrosby/go-example-webserver/server .
ENTRYPOINT ["./server"]

